import {StyleSheet} from 'react-native';

import {COLORS} from 'shared';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  header: {
    height: 150,
    width: '80%',
    backgroundColor: COLORS.dark_100,
    alignItems: 'center',
    marginBottom: 100,
  },
  profileImage: {
    width: 220,
    height: 220,
    borderRadius: 200,
    position: 'absolute',
    bottom: -100,
    backgroundColor: COLORS.dark_000,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
  },
  content: {
    flex: 1,
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    marginVertical: 40,
    backgroundColor: COLORS.dark_000,
  },
  imgContainer: {
    width: 120,
    height: 120,
  },
  inputSpace: {
    borderRadius: 8,
    paddingVertical: 5,
    elevation: 2,
    backgroundColor: COLORS.yellow_secondary,
  },
  inputText: {
    fontSize: 22,
    color: COLORS.text_primary,
  },
  languagePicker: {
    width: '100%',
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 8,
    elevation: 2,
    alignSelf: 'flex-end',
    backgroundColor: COLORS.dark_000,
    borderWidth: 1,
    borderColor: COLORS.dark_100,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  languagePickerText: {
    color: COLORS.text_primary,
    fontSize: 20,
    fontWeight: '500',
  },
  editBtn: {
    width: 50,
    height: 50,
    position: 'absolute',
    backgroundColor: COLORS.red_primary,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: COLORS.dark_100,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 64,
  },
  LanguageDialogContainer: {
    backgroundColor: COLORS.yellow_secondary,
    borderWidth: 3,
    borderColor: COLORS.dark_100,
    borderRadius: 32,
    margin: 30,
    overflow: 'hidden',
  },
  languageItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.dark_100,
  },
  languageItemText: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.red_primary,
  },
  profileImageDialogContainer: {
    backgroundColor: COLORS.yellow_secondary,
    borderWidth: 3,
    borderColor: COLORS.dark_000,
    borderRadius: 32,
    margin: 22,
    marginBottom: 64,
    overflow: 'hidden',
    flexWrap: 'wrap',
    flexDirection: 'row',
    gap: 18,
    paddingVertical: 18,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileImageItem: {
    width: 95,
    height: 95,
    borderRadius: 200,
    borderColor: 'purple',
    borderWidth: 2,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
