import {Product, PRODUCTS} from 'shared/types';

export const NEW_PRODUCTS: Product[] = [
  {
    title: {
      ru: 'Салат с тёплым лососем',
      en: 'Warm Salmon Salad',
      es: 'Ensalada De Salm\u00f3n Caliente',
      it: 'Insalata con salmone caldo',
      fr: 'Salade de saumon ti\u00e8de',
      de: 'Salat mit warmem Lachs',
      sw: 'Varm laxsallad',
      pl: 'Ciep\u0142a sa\u0142atka z \u0142ososiem',
    },
    desc: {
      ru: 'с сулугуни, апельсином, и зеленью',
      en: 'with suluguni, orange, and herbs',
      es: 'con suluguni, naranja y verdes',
      it: 'con suluguni, arancia e verdure',
      fr: 'avec suluguni, orange et l\u00e9gumes verts',
      de: 'mit Suluguni, Orange und Gr\u00fcn',
      sw: 'med suluguni, apelsin och \u00f6rter',
      pl: 'z suluguni, pomara\u0144cz\u0105 i zielenin\u0105',
    },
    price: 5,
    image: 'https://boomboomsport.website/images/sl5.png',
    type: PRODUCTS.SALADS,
    id: 0,
  },
  {
    title: {
      ru: 'Салат с жареным камамбером',
      en: 'Salad with fried camembert',
      es: 'Ensalada De Camembert Frito',
      it: 'Insalata con camembert fritto',
      fr: 'Salade au camembert po\u00eal\u00e9',
      de: 'Salat mit gebratenem Camembert',
      sw: 'Sallad med stekt camembert',
      pl: 'zielenin\u0105',
    },
    desc: {
      ru: 'с клубникой и микрозеленью',
      en: 'with strawberries and microgreens',
      es: 'con fresas y microgreens',
      it: 'con fragole e microgreens',
      fr: 'avec des fraises et des micropousses',
      de: 'mit Erdbeeren und Microgreens',
      sw: 'med jordgubbar och microgreens',
      pl: 'zielenin\u0105',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/sl6.png',
    type: PRODUCTS.SALADS,
    id: 1,
  },
  {
    title: {
      ru: 'Греческий салат',
      en: 'Greek salad',
      es: 'Ensalada griega',
      it: 'Insalata greca',
      fr: 'Salade grecque',
      de: 'griechischer Salat',
      sw: 'Grekisk sallad',
      pl: 'sa\u0142atka grecka',
    },
    desc: {
      ru: 'с творожным сыром и бальзамическим соусом',
      en: 'with cream cheese and balsamic sauce',
      es: 'con reques\u00f3n y salsa bals\u00e1mica',
      it: 'con ricotta e salsa balsamica',
      fr: 'avec fromage cottage et sauce balsamique',
      de: 'mit H\u00fcttenk\u00e4se und Balsamicosauce',
      sw: 'med f\u00e4rskost och balsamicos\u00e5s',
      pl: 'z serkiem \u015bmietankowym i sosem balsamicznym',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/sl7.png',
    type: PRODUCTS.SALADS,
    id: 2,
  },
  {
    title: {
      ru: 'Салат с прошутто и грушей',
      en: 'Prosciutto and Pear Salad',
      es: 'Ensalada de prosciutto y pera',
      it: 'Insalata con prosciutto e pere',
      fr: 'Salade de prosciutto et poire',
      de: 'Salat mit Prosciutto und Birne',
      sw: 'Prosciutto och p\u00e4ron sallad',
      pl: 'Sa\u0142atka z szynk\u0105 parme\u0144sk\u0105 i gruszk\u0105',
    },
    desc: {
      ru: 'с хрустящми гренками и базиликом',
      en: 'with crispy croutons and basil',
      es: 'con picatostes crujientes y albahaca',
      it: 'con crostini croccanti e basilico',
      fr: 'avec cro\u00fbtons croustillants et basilic',
      de: 'mit knusprigen Croutons und Basilikum',
      sw: 'med krispiga krutonger och basilika',
      pl: 'z chrupi\u0105cymi grzankami i bazyli\u0105',
    },
    price: 5,
    image: 'https://boomboomsport.website/images/sl8.png',
    type: PRODUCTS.SALADS,
    id: 3,
  },
  {
    title: {
      ru: 'Салат с телятиной',
      en: 'Salad with veal',
      es: 'Ensalada de ternera',
      it: 'Insalata di vitello',
      fr: 'Salade de veau',
      de: 'Kalbssalat',
      sw: 'Sallad med kalvk\u00f6tt',
      pl: 'Sa\u0142atka z ciel\u0119cin\u0105',
    },
    desc: {
      ru: 'с ягодами и кисло-сладким соусом',
      en: 'with berries and sweet and sour sauce',
      es: 'con frutos rojos y salsa agridulce',
      it: 'con frutti di bosco e salsa agrodolce',
      fr: 'avec des baies et une sauce aigre-douce',
      de: 'mit Beeren und S\u00fc\u00df-Sauer-Sauce',
      sw: 'med b\u00e4r och s\u00f6tsur s\u00e5s',
      pl: 'z jagodami i sosem s\u0142odko-kwa\u015bnym',
    },
    price: 5,
    image: 'https://boomboomsport.website/images/sl9.png',
    type: PRODUCTS.SALADS,
    id: 4,
  },
  {
    title: {
      ru: 'Боул вегатерианский',
      en: 'Vegetarian bowl',
      es: 'Taz\u00f3n vegetariano',
      it: 'Ciotola vegetariana',
      fr: 'Bol v\u00e9g\u00e9tarien',
      de: 'Sch\u00fcssel vegetarisch',
      sw: 'vegetarisk sk\u00e5l',
      pl: 'Miska wegetaria\u0144ska',
    },
    desc: {
      ru: 'батат,авокадо,шпинат, капуста цветная, спаржа, капуста краснокочанная помидор',
      en: 'sweet potato, avocado, spinach, cauliflower, asparagus, red cabbage, tomato',
      es: 'batata, aguacate, espinacas, coliflor, esp\u00e1rragos, col lombarda, tomate',
      it: 'patata dolce, avocado, spinaci, cavolfiore, asparagi, cavolo rosso, pomodoro',
      fr: 'patate douce, avocat, \u00e9pinards, chou-fleur, asperges, chou rouge, tomate',
      de: 'S\u00fc\u00dfkartoffel, Avocado, Spinat, Blumenkohl, Spargel, Rotkohl, Tomate',
      sw: 's\u00f6tpotatis, avokado, spenat, blomk\u00e5l, sparris, r\u00f6dk\u00e5l, tomat',
      pl: 's\u0142odkie ziemniaki, awokado, szpinak, kalafior, szparagi, czerwona kapusta, pomidor',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/sl1.png',
    type: PRODUCTS.SALADS,
    id: 5,
  },
  {
    title: {
      ru: 'Боул с курицей и авокадо',
      en: 'Chicken Avocado Bowl',
      es: 'Taz\u00f3n con pollo y aguacate',
      it: 'Taz\u00f3n con pollo y aguacate',
      fr: 'Bol de poulet et avocat',
      de: 'Sch\u00fcssel mit H\u00fchnchen und Avocado',
      sw: 'Kyckling avokado sk\u00e5l',
      pl: 'Miska z kurczakiem i awokado',
    },
    desc: {
      ru: 'курица,авокадо,морковь,лук,нут',
      en: 'chicken, avocado, carrots, onions, chickpeas',
      es: 'pollo, aguacate, zanahorias, cebollas, garbanzos',
      it: 'pollo, avocado, carote, cipolle, ceci',
      fr: 'poulet, avocat, carottes, oignons, pois chiches',
      de: 'Huhn, Avocado, Karotten, Zwiebeln, Kichererbsen',
      sw: 'kyckling, avokado, mor\u00f6tter, l\u00f6k, kik\u00e4rter',
      pl: 'kurczak, awokado, marchewka, cebula, ciecierzyca',
    },
    price: 5,
    image: 'https://boomboomsport.website/images/sl2.png',
    type: PRODUCTS.SALADS,
    id: 6,
  },
  {
    title: {
      ru: 'Салат Цезарь',
      en: 'Caesar salad',
      es: 'Ensalada Cesar',
      it: 'Insalata Cesare',
      fr: 'Salade C\u00e9sar',
      de: 'Caesar-Salat',
      sw: 'Caesar sallad',
      pl: 'sa\u0142atka cesarska',
    },
    desc: {
      ru: 'салат айсберг,курица,пармезан,черри',
      en: 'iceberg lettuce, chicken, parmesan, cherry',
      es: 'lechuga iceberg, pollo, parmesano, cereza',
      it: 'lattuga iceberg, pollo, parmigiana, ciliegia',
      fr: 'laitue iceberg, poulet, parmesan, cerise',
      de: 'Eisbergsalat, H\u00fchnchen, Parmesan, Kirsche',
      sw: 'isbergssallad, kyckling, parmesan, k\u00f6rsb\u00e4r',
      pl: 'sa\u0142ata lodowa, kurczak, parmezan, wi\u015bnia',
    },
    price: 3,
    image: 'https://boomboomsport.website/images/sl3.png',
    type: PRODUCTS.SALADS,
    id: 7,
  },
  {
    title: {
      ru: 'Салат закусочный',
      en: 'Snack salad',
      es: 'Ensalada de bocadillos',
      it: 'Insalata di spuntino',
      fr: 'Salade de collation',
      de: 'Snacksalat',
      sw: 'Snacksallad',
      pl: 'Sa\u0142atka przek\u0105skowa',
    },
    desc: {
      ru: 'авокадо, микрозелень, свекла, томаты, шпинат',
      en: 'avocado, microgreens, beets, tomatoes, spinach',
      es: 'aguacate, microverduras, remolacha, tomates, espinacas',
      it: 'avocado, microgreens, barbabietole, pomodori, spinaci',
      fr: 'avocat, micropousses, betteraves, tomates, \u00e9pinards',
      de: 'Avocado, Microgreens, R\u00fcben, Tomaten, Spinat',
      sw: 'avokado, microgreens, r\u00f6dbetor, tomater, spenat',
      pl: 'awokado, mikroli\u015bcie, buraki, pomidory, szpinak',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/sl4.png',
    type: PRODUCTS.SALADS,
    id: 8,
  },
  {
    title: {
      ru: 'Грибной крем-суп',
      en: 'Cream of mushroom soup',
      es: 'Crema de champi\u00f1ones',
      it: 'Crema di funghi',
      fr: 'Velout\u00e9 de champignons',
      de: 'Pilzcremesuppe',
      sw: 'Gr\u00e4dde av svampsoppa',
      pl: 'Zupa krem \u200b\u200bz grzyb\u00f3w',
    },
    desc: {
      ru: 'Нежнейший и ароматный крем-суп, подается вместе с гренками',
      en: 'The most delicate and aromatic cream soup, served with croutons',
      es: 'La sopa crema m\u00e1s delicada y arom\u00e1tica, servida con crutones.',
      it: 'La zuppa cremosa pi\u00f9 delicata e aromatica, servita con crostini',
      fr: 'La cr\u00e8me la plus d\u00e9licate et aromatique, servie avec des cro\u00fbtons',
      de: 'Zarte und aromatische Cremesuppe, serviert mit Croutons',
      sw: 'Den mest delikata och aromatiska gr\u00e4ddsoppan, serverad med krutonger',
      pl: 'Najdelikatniejsza i najbardziej aromatyczna zupa krem, podawana z grzankami',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/st5.png',
    type: PRODUCTS.SNACKS,
    id: 9,
  },
  {
    title: {
      ru: 'Бургер со свининой',
      en: 'Pork Burger',
      es: 'Hamburguesa de cerdo',
      it: 'Hamburger di maiale',
      fr: 'Burger de porc',
      de: 'Schweinefleischburger',
      sw: 'Fl\u00e4skburgare',
      pl: 'Burger wieprzowy',
    },
    desc: {
      ru: 'Подается с картофелем фри и соусом на выбор',
      en: 'Served with French fries and your choice of sauce',
      es: 'Servido con papas fritas y salsa de su elecci\u00f3n.',
      it: 'Servito con patatine fritte e salsa a scelta',
      fr: 'Servi avec frites et sauce de votre choix',
      de: 'Serviert mit Pommes Frites und einer Sauce nach Wahl',
      sw: 'Serveras med pommes frites och valfri s\u00e5s',
      pl: 'Podawane z frytkami i wybranym sosem',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/st6.png',
    type: PRODUCTS.SNACKS,
    id: 10,
  },
  {
    title: {
      ru: 'Цыпленок табака',
      en: 'Chicken Tabaka',
      es: 'Tabaka de pollo',
      it: 'Pollo Tabaka',
      fr: 'Tabaka au poulet',
      de: 'H\u00fchnchen-Tabak',
      sw: 'Kyckling Tabaka',
      pl: 'Kurczak Tabaka',
    },
    desc: {
      ru: 'Классический цыпленок табака, томленный в вишнево-мятном соусе',
      en: 'Classic Chicken Tabaka, Simmered in Cherry-Mint Sauce',
      es: 'Tabaka cl\u00e1sica de pollo, cocinada a fuego lento en salsa de cereza y menta',
      it: 'Classico pollo Tabaka, cotto a fuoco lento in salsa di ciliegie e menta',
      fr: 'Tabaka de poulet classique mijot\u00e9 dans une sauce cerise-menthe',
      de: 'Klassisches H\u00e4hnchen-Tabak, geschmort in Kirsch-Minz-Sauce',
      sw: 'Klassisk kycklingtabaka, sjudad i k\u00f6rsb\u00e4rsmints\u00e5s',
      pl: 'Klasyczny kurczak Tabaka, duszony w sosie wi\u015bniowo-mi\u0119towym',
    },
    price: 6,
    image: 'https://boomboomsport.website/images/st7.png',
    type: PRODUCTS.SNACKS,
    id: 11,
  },
  {
    title: {
      ru: "Суп 'Морской бриз",
      en: 'Sea Breeze Soup',
      es: 'Sopa de brisa marina',
      it: 'Zuppa di brezza marina',
      fr: 'Soupe \u00e0 la brise marine',
      de: 'Suppe \u201eMeeresbrise\u201c',
      sw: 'Sea Breeze Soppa',
      pl: 'Zupa z morsk\u0105 bryz\u0105',
    },
    desc: {
      ru: 'Насыщенный ароматный суп с мидиями, креветками и кальмарами',
      en: 'Rich aromatic soup with mussels, shrimps and squid',
      es: 'Sopa rica y arom\u00e1tica con mejillones, camarones y calamares.',
      it: 'Zuppa ricca e aromatica con cozze, gamberi e calamari',
      fr: 'Soupe riche et aromatique aux moules, crevettes et calmars',
      de: 'Reichhaltige, aromatische Suppe mit Muscheln, Garnelen und Tintenfisch',
      sw: 'Rik aromatisk soppa med musslor, r\u00e4kor och bl\u00e4ckfisk',
      pl: 'Bogata, aromatyczna zupa z ma\u0142\u017cami, krewetkami i ka\u0142amarnicami',
    },
    price: 5,
    image: 'https://boomboomsport.website/images/st8.png',
    type: PRODUCTS.SNACKS,
    id: 12,
  },
  {
    title: {
      ru: 'Куриный рулет с овощами',
      en: 'Chicken roll with vegetables',
      es: 'Rollo de pollo con verduras',
      it: 'Rotolo di pollo con verdure',
      fr: 'Rouleau de poulet aux l\u00e9gumes',
      de: 'H\u00e4hnchenbr\u00f6tchen mit Gem\u00fcse',
      sw: 'Kycklingrulle med gr\u00f6nsaker',
      pl: 'Rolada z kurczaka z warzywami',
    },
    desc: {
      ru: 'куриное филе, микс овощей, кисло-сладкий соус, кунжут',
      en: 'chicken fillet, mixed vegetables, sweet and sour sauce, sesame',
      es: 'Filete de pollo, verduras mixtas, salsa agridulce, s\u00e9samo',
      it: 'filetto di pollo, verdure miste, salsa agrodolce, sesamo',
      fr: 'filet de poulet, l\u00e9gumes m\u00e9lang\u00e9s, sauce aigre-douce, s\u00e9same',
      de: 'H\u00e4hnchenfilet, gemischtes Gem\u00fcse, S\u00fc\u00df-Sauer-Sauce, Sesam',
      sw: 'kycklingfil\u00e9, blandade gr\u00f6nsaker, s\u00f6tsur s\u00e5s, sesam',
      pl: 'filet z kurczaka, mieszane warzywa, sos s\u0142odko-kwa\u015bny, sezam',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/st1.png',
    type: PRODUCTS.SNACKS,
    id: 13,
  },
  {
    title: {
      ru: 'Утиная грудка на тыквенной подушке',
      en: 'Duck breast on a pumpkin pillow',
      es: 'Pechuga de pato sobre una almohada de calabaza',
      it: "Petto d'anatra su cuscino di zucca",
      fr: 'Magret de canard sur un coussin de citrouille',
      de: 'Entenbrust auf einem K\u00fcrbisbett',
      sw: 'Ankbr\u00f6st p\u00e5 en pumpakudde',
      pl: 'Pier\u015b kaczki na poduszce z dyni',
    },
    desc: {
      ru: 'утка, тыква, зелень, бальзамический соус',
      en: 'duck, pumpkin, greens, balsamic sauce',
      es: 'pato, calabaza, verduras, salsa bals\u00e1mica',
      it: 'anatra, zucca, verdure, salsa balsamica',
      fr: 'anatra, zucca, verdure, salsa balsamica',
      de: 'Ente, K\u00fcrbis, Gem\u00fcse, Balsamicosauce',
      sw: 'anka, pumpa, gr\u00f6na, balsamicos\u00e5s',
      pl: 'kaczka, dynia, zielenina, sos balsamiczny',
    },
    price: 5,
    image: 'https://boomboomsport.website/images/st2.png',
    type: PRODUCTS.SNACKS,
    id: 14,
  },
  {
    title: {
      ru: 'Телятина в соусе карри',
      en: 'Veal in curry sauce',
      es: 'Ternera en salsa de curry',
      it: 'Vitello in salsa al curry',
      fr: 'Veau \u00e0 la sauce au curry',
      de: 'Kalbfleisch in Currysauce',
      sw: 'Kalvk\u00f6tt i currys\u00e5s',
      pl: 'Ciel\u0119cina w sosie curry',
    },
    desc: {
      ru: 'телятина, грибы, соус карри, зелень',
      en: 'veal, mushrooms, curry sauce, herbs',
      es: 'Ternera, champi\u00f1ones, salsa de curry, hierbas',
      it: 'vitello, funghi, salsa al curry, erbe aromatiche',
      fr: 'veau, champignons, sauce curry, herbes',
      de: 'Kalbfleisch, Pilze, Currysauce, Gem\u00fcse',
      sw: 'kalvk\u00f6tt, svamp, currys\u00e5s, \u00f6rter',
      pl: 'ciel\u0119cina, pieczarki, sos curry, zio\u0142a',
    },
    price: 5,
    image: 'https://boomboomsport.website/images/st3.png',
    type: PRODUCTS.SNACKS,
    id: 15,
  },
  {
    title: {
      ru: 'Лосось запеченный',
      en: 'Baked salmon',
      es: 'Salm\u00f3n al horno',
      it: 'Salmone al forno',
      fr: 'Saumon au four',
      de: 'Gebackener Lachs',
      sw: 'Ugnsbakad lax',
      pl: 'Pieczony \u0142oso\u015b',
    },
    desc: {
      ru: 'лосось, лимонный сок, томаты',
      en: 'salmon, lemon juice, tomatoes',
      es: 'salm\u00f3n, jugo de lim\u00f3n, tomates',
      it: 'salmone, succo di limone, pomodori',
      fr: 'saumon, jus de citron, tomates',
      de: 'Lachs, Zitronensaft, Tomaten',
      sw: 'lax, citronsaft, tomater',
      pl: '\u0142oso\u015b, sok z cytryny, pomidory',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/st4.png',
    type: PRODUCTS.SNACKS,
    id: 16,
  },
  {
    title: {
      ru: 'Лосось запеченный',
      en: 'Creme Brulee',
      es: 'Cr\u00e8me br\u00fbl\u00e9e',
      it: 'Crema Brul\u00e9e',
      fr: 'Cr\u00e8me br\u00fbl\u00e9e',
      de: 'Cr\u00e8me Br\u00fbl\u00e9e',
      sw: 'Creme Brulee',
      pl: 'Creme Brulee',
    },
    desc: {
      ru: 'лосось, лимонный сок, томаты',
      en: 'Creamy delicate dessert with fresh berries',
      es: 'Postre cremoso y delicado con bayas frescas.',
      it: 'Dessert cremoso e delicato con frutti di bosco freschi',
      fr: 'Dessert d\u00e9licat et cr\u00e9meux aux baies fra\u00eeches',
      de: 'Cremiges, zartes Dessert mit frischen Beeren',
      sw: 'Kr\u00e4mig delikat dessert med f\u00e4rska b\u00e4r',
      pl: 'Kremowy delikatny deser ze \u015bwie\u017cymi jagodami',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/ds5.png',
    type: PRODUCTS.DESERTS,
    id: 17,
  },
  {
    title: {
      ru: 'Веганский торт',
      en: 'Vegan cake',
      es: 'Pastel vegano',
      it: 'Torta vegana',
      fr: 'G\u00e2teau v\u00e9g\u00e9talien',
      de: 'Veganer Kuchen',
      sw: 'Vegansk t\u00e5rta',
      pl: 'Ciasto wega\u0144skie',
    },
    desc: {
      ru: 'Без глютена на кокосовом молоке, с ароматной фисташкой',
      en: 'Gluten free coconut milk with aromatic pistachio',
      es: 'Leche de coco sin gluten con pistacho arom\u00e1tico',
      it: 'Latte di cocco senza glutine con pistacchio aromatico',
      fr: 'Lait de coco sans gluten aux pistaches aromatiques',
      de: 'Glutenfreie Kokosmilch mit aromatischer Pistazie',
      sw: 'Glutenfri kokosmj\u00f6lk med aromatisk pistage',
      pl: 'Mleko kokosowe bezglutenowe z aromatycznymi pistacjami',
    },
    price: 3,
    image: 'https://boomboomsport.website/images/ds6.png',
    type: PRODUCTS.DESERTS,
    id: 18,
  },
  {
    title: {
      ru: 'Манговый чиз',
      en: 'Mango cheese',
      es: 'Queso de mango',
      it: 'Formaggio al mango',
      fr: 'Fromage \u00e0 la mangue',
      de: 'Mangok\u00e4se',
      sw: 'Mango ost',
      pl: 'Ser mango',
    },
    desc: {
      ru: 'Ароматный легкий десерт, с нотками мяты и манго',
      en: 'A fragrant light dessert with notes of mint and mango',
      es: 'Un postre ligero y fragante con notas de menta y mango.',
      it: 'Un dessert leggero e profumato con note di menta e mango',
      fr: 'Un dessert l\u00e9ger et parfum\u00e9 aux notes de menthe et de mangue',
      de: 'Ein duftendes, leichtes Dessert mit Noten von Minze und Mango',
      sw: 'En v\u00e4ldoftande l\u00e4tt dessert med toner av mynta och mango',
      pl: 'Pachn\u0105cy, lekki deser z nutami mi\u0119ty i mango',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/ds7.png',
    type: PRODUCTS.DESERTS,
    id: 19,
  },
  {
    title: {
      ru: 'Бананы в темпуре',
      en: 'Bananas in tempura',
      es: 'Pl\u00e1tanos en tempura',
      it: 'Banane in tempura',
      fr: 'Bananes en tempura',
      de: 'Bananen-Tempura',
      sw: 'Bananer i tempura',
      pl: 'Banany w tempurze',
    },
    desc: {
      ru: 'Низкокалорийный десерт, покрытый темным шоколадом',
      en: 'Low-calorie dessert covered in dark chocolate',
      es: 'Postre bajo en calor\u00edas cubierto de chocolate negro',
      it: 'Dolce ipocalorico ricoperto di cioccolato fondente',
      fr: 'Dessert hypocalorique enrob\u00e9 de chocolat noir',
      de: 'Kalorienarmes Dessert umh\u00fcllt von dunkler Schokolade',
      sw: 'Kalorifattig dessert t\u00e4ckt av m\u00f6rk choklad',
      pl: 'Niskokaloryczny deser oblany gorzk\u0105 czekolad\u0105',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/ds8.png',
    type: PRODUCTS.DESERTS,
    id: 20,
  },
  {
    title: {
      ru: 'Тыквенный мусс',
      en: 'Pumpkin mousse',
      es: 'Mousse de calabaza',
      it: 'Mousse di zucca',
      fr: 'Mousse de potiron',
      de: 'K\u00fcrbismousse',
      sw: 'Pumpamousse',
      pl: 'Mus dyniowy',
    },
    desc: {
      ru: 'Тыква, сезонные ягоды, ягодный сироп',
      en: 'pumpkin, seasonal berries, berry syrup',
      es: 'Calabaza, frutos rojos de temporada, sirope de frutos rojos',
      it: 'zucca, bacche di stagione, sciroppo di bacche',
      fr: 'citrouille, baies de saison, sirop de baies',
      de: 'K\u00fcrbis, Beeren der Saison, Beerensirup',
      sw: 'pumpa, s\u00e4songens b\u00e4r, b\u00e4rsirap',
      pl: 'dynia, sezonowe jagody, syrop jagodowy',
    },
    price: 3,
    image: 'https://boomboomsport.website/images/ds1.png',
    type: PRODUCTS.DESERTS,
    id: 21,
  },
  {
    title: {
      ru: "Десерт 'Рафаэлло",
      en: "Dessert 'Rafaello'",
      es: "Postre 'Rafaello'",
      it: "Dolce 'Raffaello'",
      fr: "Dessert 'Rafaello'",
      de: "Dessert 'Raffaello'",
      sw: "Dessert 'Rafaello'",
      pl: 'Deser \u201eRafaello\u201d',
    },
    desc: {
      ru: 'Бисквит, сливочный крем, кокосовая стружка',
      en: 'biscuit, butter cream, coconut flakes',
      es: 'galleta, crema de mantequilla, hojuelas de coco',
      it: 'biscotto, crema al burro, scaglie di cocco',
      fr: 'biscuit, cr\u00e8me au beurre, flocons de noix de coco',
      de: 'Biskuitkuchen, Buttercreme, Kokosflocken',
      sw: 'kex, sm\u00f6rkr\u00e4m, kokosflingor',
      pl: 'biszkopt, krem \u200b\u200bma\u015blany, wi\u00f3rki kokosowe',
    },
    price: 3,
    image: 'https://boomboomsport.website/images/ds2.png',
    type: PRODUCTS.DESERTS,
    id: 22,
  },
  {
    title: {
      ru: 'Шоколадные маффины',
      en: 'Chocolate Muffins',
      es: 'Muffins de chocolate',
      it: 'Muffin al cioccolato',
      fr: 'Muffins au chocolat',
      de: 'Schokoladenmuffins',
      sw: 'Chokladmuffins',
      pl: 'Muffinki czekoladowe',
    },
    desc: {
      ru: 'Маффин, с крем-чизом и ягодами',
      en: 'muffin with cream cheese and berries',
      es: 'Muffin con queso crema y frutos rojos',
      it: 'muffin con crema di formaggio e frutti di bosco',
      fr: 'muffin au fromage \u00e0 la cr\u00e8me et aux baies',
      de: 'Muffin mit Frischk\u00e4se und Beeren',
      sw: 'muffins med f\u00e4rskost och b\u00e4r',
      pl: 'muffinka z serkiem \u015bmietankowym i jagodami',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/ds3.png',
    type: PRODUCTS.DESERTS,
    id: 23,
  },
  {
    title: {
      ru: "Торт 'Ежевичный вечер",
      en: "Cake 'Blackberry Evening'",
      es: "Pastel 'Noche de Moras'",
      it: "Torta 'Serata di more'",
      fr: 'G\u00e2teau \u00ab Soir\u00e9e aux m\u00fbres \u00bb',
      de: "Kuchen 'Brombeerabend'",
      sw: "Cake 'Blackberry Evening'",
      pl: 'Ciasto \u201eJe\u017cynowy Wiecz\u00f3r\u201d',
    },
    desc: {
      ru: 'Мусс из ягод ежевики и вишни, со сливочным кремом',
      en: 'blackberry and cherry mousse with butter cream',
      es: 'Mousse de mora y cereza con crema de mantequilla',
      it: 'mousse di more e ciliegie con crema al burro',
      fr: 'mousse aux m\u00fbres et aux cerises avec cr\u00e8me au beurre',
      de: 'Brombeer-Kirsch-Mousse mit Buttercreme',
      sw: 'bj\u00f6rnb\u00e4rs- och k\u00f6rsb\u00e4rsmousse med sm\u00f6rkr\u00e4m',
      pl: 'mus je\u017cynowy i wi\u015bniowy z kremem ma\u015blanym',
    },
    price: 3,
    image: 'https://boomboomsport.website/images/ds4.png',
    type: PRODUCTS.DESERTS,
    id: 24,
  },
  {
    title: {
      ru: 'Лимонад',
      en: 'Lemonade',
      es: 'Limonada',
      it: 'Limonata',
      fr: 'Limonade',
      de: 'Limonade',
      sw: 'Lemonad',
      pl: 'Lemoniada',
    },
    desc: {
      ru: 'Освежающий ароматный лимонад',
      en: 'Refreshing aromatic lemonade',
      es: 'Limonada refrescante y arom\u00e1tica',
      it: 'Limonata aromatica rinfrescante',
      fr: 'Limonade aromatique rafra\u00eechissante',
      de: 'Erfrischende aromatisierte Limonade',
      sw: 'Uppfriskande aromatisk lemonad',
      pl: 'Orze\u017awiaj\u0105ca aromatyczna lemoniada',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/dr5.png',
    type: PRODUCTS.DRINKS,
    id: 25,
  },
  {
    title: {
      ru: 'Авторские чаи',
      en: 'Designer teas',
      es: 'T\u00e9s de dise\u00f1o',
      it: 'T\u00e8 di design',
      fr: 'Th\u00e9s de cr\u00e9ateurs',
      de: 'Tees des Autors',
      sw: 'Designer teer',
      pl: 'Herbaty designerskie',
    },
    desc: {
      ru: 'Цитрусовый / Облепиховый / Молочный / Мятный',
      en: 'Citrus / Sea Buckthorn / Milky / Mint',
      es: 'C\u00edtricos / Espino amarillo / L\u00e1cteo / Menta',
      it: 'Agrumi / Olivello spinoso / Latteo / Menta',
      fr: 'Agrumes / Argousier / Lact\u00e9 / Menthe',
      de: 'Zitrusfr\u00fcchte / Sanddorn / Milch / Minze',
      sw: 'Citrus / Havtorn / Milky / Mint',
      pl: 'Cytrusowy / Rokitnikowy / Mleczny / Mi\u0119towy',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/dr6.png',
    type: PRODUCTS.DRINKS,
    id: 26,
  },
  {
    title: {
      ru: 'Молочный коктейль',
      en: 'Milkshake',
      es: 'Batido',
      it: 'Frapp\u00e8',
      fr: 'Milk-shake',
      de: 'Milchshake',
      sw: 'Milkshake',
      pl: 'Koktajl mleczny',
    },
    desc: {
      ru: 'В составе - молоко, мороженое, кофейный сироп',
      en: 'Ingredients: milk, ice cream, coffee syrup',
      es: 'Ingredientes: leche, helado, jarabe de caf\u00e9.',
      it: 'Ingredienti: latte, gelato, sciroppo di caff\u00e8',
      fr: 'Ingr\u00e9dients : lait, glace, sirop de caf\u00e9',
      de: 'Zutaten: Milch, Eis, Kaffeesirup',
      sw: 'Ingredienser: mj\u00f6lk, glass, kaffesirap',
      pl: 'Sk\u0142adniki: mleko, lody, syrop kawowy',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/dr7.png',
    type: PRODUCTS.DRINKS,
    id: 27,
  },
  {
    title: {
      ru: 'Бамбл',
      en: 'Bumble',
      es: 'Andar a tropezones',
      it: 'Bombo',
      fr: 'Bourdonnement',
      de: 'Hummel',
      sw: 'Bumble',
      pl: 'B\u0105czek',
    },
    desc: {
      ru: 'Холодный напиток на основе апельсинового сока и эспрессо',
      en: 'Cold drink based on orange juice and espresso',
      es: 'Bebida fr\u00eda a base de zumo de naranja y espresso.',
      it: "Bevanda fredda a base di succo d'arancia ed espresso",
      fr: "Boisson froide \u00e0 base de jus d'orange et d'espresso",
      de: 'Kaltgetr\u00e4nk auf Basis von Orangensaft und Espresso',
      sw: 'Kall dryck baserad p\u00e5 apelsinjuice och espresso',
      pl: 'Zimny \u200b\u200bnap\u00f3j na bazie soku pomara\u0144czowego i espresso',
    },
    price: 2,
    image: 'https://boomboomsport.website/images/dr8.png',
    type: PRODUCTS.DRINKS,
    id: 28,
  },
  {
    title: {
      ru: "Коктейль 'Беллини",
      en: 'Bellini Cocktail',
      es: 'C\u00f3ctel Bellini',
      it: 'Cocktail Bellini',
      fr: 'Cocktail Bellini',
      de: "Cocktail 'Bellini'",
      sw: 'Bellini cocktail',
      pl: 'Koktajl Bellini',
    },
    desc: {
      ru: 'вино игристое, персиковое пюре',
      en: 'sparkling wine, peach puree',
      es: 'vino espumoso, pur\u00e9 de melocot\u00f3n',
      it: 'spumante, purea di pesca',
      fr: 'vin mousseux, pur\u00e9e de p\u00eache',
      de: 'Sekt, Pfirsichp\u00fcree',
      sw: 'mousserande vin, persikopur\u00e9',
      pl: 'wino musuj\u0105ce, puree brzoskwiniowe',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/dr1.png',
    type: PRODUCTS.DRINKS,
    id: 29,
  },
  {
    title: {
      ru: "Коктейль 'Кровавая Мэри",
      en: 'Bloody Mary Cocktail',
      es: 'C\u00f3ctel Bloody Mary',
      it: 'Cocktail di Bloody Mary',
      fr: 'Cocktail Bloody Mary',
      de: 'Cocktail \u201eBloody Mary\u201c',
      sw: 'Bloody Mary Cocktail',
      pl: 'Koktajl Krwawa Mary',
    },
    desc: {
      ru: 'водка, томатный сок, сельдерей, лед',
      en: 'vodka, tomato juice, celery, ice',
      es: 'vodka, jugo de tomate, apio, hielo',
      it: 'vodka, succo di pomodoro, sedano, ghiaccio',
      fr: 'vodka, jus de tomate, c\u00e9leri, glace',
      de: 'Wodka, Tomatensaft, Sellerie, Eis',
      sw: 'vodka, tomatjuice, selleri, is',
      pl: 'w\u00f3dka, sok pomidorowy, seler, l\u00f3d',
    },
    price: 3,
    image: 'https://boomboomsport.website/images/dr2.png',
    type: PRODUCTS.DRINKS,
    id: 30,
  },
  {
    title: {
      ru: "Коктейль 'Виски-кола'",
      en: 'Whiskey-Cola cocktail',
      es: 'C\u00f3ctel de whisky y cola',
      it: 'Cocktail Whisky-Cola',
      fr: 'Cocktail Whisky-Cola',
      de: 'Whiskey-Cola-Cocktail',
      sw: 'Whisky-Cola cocktail',
      pl: 'Koktajl Whiskey-Cola',
    },
    desc: {
      ru: 'виски, кола, лимон, лед',
      en: 'whiskey, cola, lemon, ice',
      es: 'Whisky, cola, lim\u00f3n, hielo',
      it: 'whisky, cola, limone, ghiaccio',
      fr: 'whisky, cola, citron, glace',
      de: 'Whiskey, Cola, Zitrone, Eis',
      sw: 'whisky, cola, citron, is',
      pl: 'whisky, cola, cytryna, l\u00f3d',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/dr3.png',
    type: PRODUCTS.DRINKS,
    id: 31,
  },
  {
    title: {
      ru: "Коктейль 'Дайкири'",
      en: "Cocktail 'Daiquiri'",
      es: "C\u00f3ctel 'Daiquiri'",
      it: "Cocktail 'Daiquiri'",
      fr: "Cocktail 'Daiquiri'",
      de: "Cocktail 'Daiquiri'",
      sw: "Cocktail 'Daiquiri'",
      pl: 'Koktajl \u201eDaiquiri\u201d',
    },
    desc: {
      ru: 'белый ром, лайм, сахарный сироп',
      en: 'white rum, lime, sugar syrup',
      es: 'Ron blanco, lima, jarabe de az\u00facar',
      it: 'rum bianco, lime, sciroppo di zucchero',
      fr: 'rhum blanc, citron vert, sirop de sucre',
      de: 'wei\u00dfer Rum, Limette, Zuckersirup',
      sw: 'vit rom, lime, sockersirap',
      pl: 'bia\u0142y rum, limonka, syrop cukrowy',
    },
    price: 4,
    image: 'https://boomboomsport.website/images/dr4.png',
    type: PRODUCTS.DRINKS,
    id: 32,
  },
];
